name: check-tf-version

on:
  workflow_dispatch:
    inputs:
      TERRAFORM_VERSION:
        description: 'Terraform version to use'
        required: false
        default: ''

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Set TERRAFORM_VERSION environment variable
        id: set-tf-ver
        run: |
          if [ -z "${{ github.event.inputs.TERRAFORM_VERSION }}" ]; then
            echo "TERRAFORM_VERSION not supplied. Fetching the latest version..."
            # Fetch the latest Terraform version from the HashiCorp API
            TERRAFORM_VERSION=$(curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r .current_version)
          else
            TERRAFORM_VERSION="${{ github.event.inputs.TERRAFORM_VERSION }}"
          fi
          echo "TERRAFORM_VERSION=${TERRAFORM_VERSION}" >> $GITHUB_ENV

      - name: Print TERRAFORM_VERSION
        run: |
          echo "TERRAFORM_VERSION is set to $TERRAFORM_VERSION"

      - name: Setup Docker Container
        run: |
          docker build -t custom-alpine-terraform .

      - name: Run Docker Container
        run: |
          docker compose up -d
      
      - name: Check Terraform Version
        run: |
          docker exec alpine_container terraform --version
