name: check-tf-version

on:
  workflow_dispatch:
    inputs:
      TF_VER:
        description: 'Terraform version to use'
        required: false
        default: ''

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Set TF_VER environment variable
        id: set-tf-ver
        run: |
          if [ -z "${{ github.event.inputs.TF_VER }}" ]; then
            echo "TF_VER not supplied. Fetching the latest version..."
            # Fetch the latest Terraform version from the HashiCorp API
            TF_VER=$(curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r .current_version)
          else
            TF_VER="${{ github.event.inputs.TF_VER }}"
          fi
          echo "TF_VER=${TF_VER}" >> $GITHUB_ENV

      - name: Print TF_VER
        run: |
          echo "TF_VER is set to $TF_VER"

      - name: Run Terraform Setup
        run: |
          echo "Setting up Terraform version $TF_VER..."
